from .belt import Belt
from .cube import Cube
from .death import Death
from .difficulty_select import DifficultySelect
from .hud import Hud
from .left_inventory import LeftInventory
from .loading import Loading
from .main_menu import MainMenu
from .right_inventory import RightInventory
from .save_and_exit import SaveAndExit
from .screen_object import ScreenObject
from .waypoint import Waypoint