CONSUMABLES = {
    'MINOR HEALING POTION': ['MINOR_HEALING_POTION', 'BELT_MINOR_HEALING_POTION'],
    'LIGHT HEALING POTION': ['LIGHT_HEALING_POTION', 'BELT_LIGHT_HEALING_POTION'],
    'HEALING POTION': ['HEALING_POTION', 'BELT_HEALING_POTION'],
    'GREATER HEALING POTION': ['GREATER_HEALING_POTION', 'BELT_GREATER_HEALING_POTION'],
    'SUPER HEALING POTION': ['SUPER_HEALING_POTION', 'BELT_SUPER_HEALING_POTION'],
    #
    'MINOR MANA POTION': ['MINOR_MANA_POTION', 'BELT_MINOR_MANA_POTION'],
    'LIGHT MANA POTION': ['LIGHT_MANA_POTION', 'BELT_LIGHT_MANA_POTION'],
    'MANA POTION': ['MANA_POTION', 'BELT_MANA_POTION'],
    'GREATER MANA POTION': ['GREATER_MANA_POTION', 'BELT_GREATER_MANA_POTION'],
    'SUPER MANA POTION': ['SUPER_MANA_POTION', 'BELT_SUPER_MANA_POTION'],
    #
    'REJUVENATION POTION': ['REJUV_POTION', 'BELT_REJUV_POTION'],
    'FULL REJUVENATION POTION': ['FULL_REJUV_POTION', 'BELT_FULL_REJUV_POTION'],
    #
    'ANTIDOTE POTION': ['ANTIDOTE_POTION', 'BELT_ANTIDOTE_POTION'],
    'STAMINA POTION': ['STAMINA_POTION', 'BELT_STAMINA_POTION'],
    'THAWING POTION': ['THAWING_POTION', 'BELT_THAWING_POTION'],
    #
    'SCROLL OF IDENTIFY': ['ID_SCROLL', 'BELT_ID_SCROLL'],
    'SCROLL OF TOWN PORTAL': ['TP_SCROLL', 'BELT_TP_SCROLL'],
    #
    'KEY': ['KEY'],
    #
    'ARROWS': ['ARROWS'],
    'BOLTS': ['BOLTS'],
}

EMPTY_BELT_SLOT = {'EMPTY BELT SLOT': ['BELT_EMPTY_SLOT']}

CHARMS = {
    'GRAND CHARM': ['GC1', 'GC2'],
    'SMALL CHARM': ['SC1', 'SC2', 'SC3']
}

GEMS = {
    'CHIPPED AMETHYST': ['CHIPPED_AMETHYST'],
    'FLAWED AMETHYST': ['FLAWED_AMETHYST'],
    'AMETHYST': ['AMETHYST'],
    'FLAWLESS AMETHYST': ['FLAWLESS_AMETHYST'],
    'PERFECT AMETHYST': ['PERFECT_AMETHYST'],
    #
    'CHIPPED TOPAZ': ['CHIPPED_TOPAZ'],
    'FLAWED TOPAZ': ['FLAWED_TOPAZ'],
    'TOPAZ': ['TOPAZ'],
    'FLAWLESS TOPAZ': ['FLAWLESS_TOPAZ'],
    'PERFECT TOPAZ': ['PERFECT_TOPAZ'],
    #
    'CHIPPED DIAMOND': ['CHIPPED_DIAMOND'],
    'FLAWED DIAMOND': ['FLAWED_DIAMOND'],
    'DIAMOND': ['DIAMOND'],
    'FLAWLESS DIAMOND': ['FLAWLESS_DIAMOND'],
    'PERFECT DIAMOND': ['PERFECT_DIAMOND'],
    #
    'CHIPPED EMERALD': ['CHIPPED_EMERALD'],
    'FLAWED EMERALD': ['FLAWED_EMERALD'],
    'EMERALD': ['EMERALD'],
    'FLAWLESS EMERALD': ['FLAWLESS_EMERALD'],
    'PERFECT EMERALD': ['PERFECT_EMERALD'],
    #
    'CHIPPED RUBY': ['CHIPPED_RUBY'],
    'FLAWED RUBY': ['FLAWED_RUBY'],
    'RUBY': ['RUBY'],
    'FLAWLESS RUBY': ['FLAWLESS_RUBY'],
    'PERFECT RUBY': ['PERFECT_RUBY'],
    #
    'CHIPPED SAPPHIRE': ['CHIPPED_SAPPHIRE'],
    'FLAWED SAPPHIRE': ['FLAWED_SAPPHIRE'],
    'SAPPHIRE': ['SAPPHIRE'],
    'FLAWLESS SAPPHIRE': ['FLAWLESS_SAPPHIRE'],
    'PERFECT SAPPHIRE': ['PERFECT_SAPPHIRE'],
    #
    'CHIPPED SKULL': ['CHIPPED_SKULL'],
    'FLAWED SKULL': ['FLAWED_SKULL'],
    'SKULL': ['SKULL'],
    'FLAWLESS SKULL': ['FLAWLESS_SKULL'],
    'PERFECT SKULL': ['PERFECT_SKULL'],
}

RUNES = {
    'EL RUNE': ['EL'],
    'ELD RUNE': ['ELD'],
    'TIR RUNE': ['TIR'],
    'NEF RUNE': ['NEF'],
    'ETH RUNE': ['ETH'],
    'ITH RUNE': ['ITH'],
    'TAL RUNE': ['TAL'],
    'RAL RUNE': ['RAL'],
    'ORT RUNE': ['ORT'],
    'THUL RUNE': ['THUL'],
    'AMN RUNE': ['AMN'],
    'SOL RUNE': ['SOL'],
    'SHAEL RUNE': ['SHAEL'],
    'DOL RUNE': ['DOL'],
    'HEL RUNE': ['HEL'],
    'IO RUNE': ['IO'],
    'LUM RUNE': ['LUM'],
    'KO RUNE': ['KO'],
    'FAL RUNE': ['FAL'],
    'LEM RUNE': ['LEM'],
    'PUL RUNE': ['PUL'],
    'UM RUNE': ['UM'],
    'MAL RUNE': ['MAL'],
    'IST RUNE': ['IST'],
    'GUL RUNE': ['GUL'],
    'VEX RUNE': ['VEX'],
    'OHM RUNE': ['OHM'],
    'LO RUNE': ['LO'],
    'SUR RUNE': ['SUR'],
    'BER RUNE': ['BER'],
    'JAH RUNE': ['JAH'],
    'CHAM RUNE': ['CHAM'],
    'ZOD RUNE': ['ZOD'],
}

LEFT_INVENTORY_MAP = {**CONSUMABLES, **CHARMS, **GEMS, **RUNES}
RIGHT_INVENTORY_MAP = {**CONSUMABLES, **CHARMS, **GEMS, **RUNES}
BELT_MAP = {**CONSUMABLES, **EMPTY_BELT_SLOT}