name: GitHub Actions - Tests
on: [push]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}
      - name: Install Dependencies
        shell: cmd
        run: |
          C:\Miniconda\condabin\conda.bat env create environment.yml
      - name: Pytest
        shell: cmd
        run: |
          C:\Miniconda\condabin\conda.bat activate botty
          python -c "import sys; print(sys.version)"
          python -m pytest -v
